# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.0
jobs:
  build:
    working_directory: ~/circleci-Pineapple
    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout
      - restore_cache:
        key: circleci-Pineapple-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
        paths:
          - ~/.m2
        key: circleci-Pineapple-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
        path: target/surefire-reports
      - store_artifacts:
        path: target/MavenPineapple-1.0-SNAPSHOT.jar