# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.0
jobs:
  build:
    working_directory: ~/circleci-Pineapple
    docker:
      - image: circleci/openjdk:11-jdk-stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

orbs:
  maven: circleci/maven@1.2.0

workflows:
  maven_test:
    jobs:
      - maven/test
